import type { CSSProperties } from 'react';

type HljsTheme = Record<string, CSSProperties>;

const forgeDark: HljsTheme = {
  hljs: { display: 'block', overflowX: 'auto', color: '#ebdbb2' },
  'hljs-comment': { color: '#928374', fontStyle: 'italic' },
  'hljs-quote': { color: '#928374', fontStyle: 'italic' },
  'hljs-keyword': { color: '#fb4934' },
  'hljs-selector-tag': { color: '#fb4934' },
  'hljs-literal': { color: '#d3869b' },
  'hljs-number': { color: '#d3869b' },
  'hljs-string': { color: '#b8bb26' },
  'hljs-doctag': { color: '#b8bb26' },
  'hljs-template-variable': { color: '#fe8019' },
  'hljs-variable': { color: '#fe8019' },
  'hljs-title': { color: '#83a598' },
  'hljs-section': { color: '#83a598', fontWeight: 'bold' },
  'hljs-type': { color: '#fabd2f' },
  'hljs-class .hljs-title': { color: '#fabd2f' },
  'hljs-built_in': { color: '#8ec07c' },
  'hljs-name': { color: '#8ec07c' },
  'hljs-tag': { color: '#928374' },
  'hljs-attr': { color: '#b8bb26' },
  'hljs-attribute': { color: '#ebdbb2' },
  'hljs-meta': { color: '#d5c4a1' },
  'hljs-meta-keyword': { color: '#d5c4a1' },
  'hljs-meta-string': { color: '#b8bb26' },
  'hljs-regexp': { color: '#fe8019' },
  'hljs-link': { color: '#83a598' },
  'hljs-symbol': { color: '#d3869b' },
  'hljs-bullet': { color: '#d3869b' },
  'hljs-subst': { color: '#ebdbb2' },
  'hljs-selector-id': { color: '#83a598' },
  'hljs-selector-class': { color: '#83a598' },
  'hljs-selector-attr': { color: '#b8bb26' },
  'hljs-selector-pseudo': { color: '#8ec07c' },
  'hljs-addition': { color: '#b8bb26', backgroundColor: 'rgba(184,187,38,0.15)' },
  'hljs-deletion': { color: '#fb4934', backgroundColor: 'rgba(251,73,52,0.15)' },
  'hljs-emphasis': { fontStyle: 'italic' },
  'hljs-strong': { fontWeight: 'bold' },
  'hljs-params': { color: '#ebdbb2' },
  'hljs-operator': { color: '#fe8019' },
  'hljs-punctuation': { color: '#ebdbb2' },
  'hljs-property': { color: '#8ec07c' },
};

const forgeLight: HljsTheme = {
  hljs: { display: 'block', overflowX: 'auto', color: '#3c3836' },
  'hljs-comment': { color: '#928374', fontStyle: 'italic' },
  'hljs-quote': { color: '#928374', fontStyle: 'italic' },
  'hljs-keyword': { color: '#9d0006' },
  'hljs-selector-tag': { color: '#9d0006' },
  'hljs-literal': { color: '#8f3f71' },
  'hljs-number': { color: '#8f3f71' },
  'hljs-string': { color: '#79740e' },
  'hljs-doctag': { color: '#79740e' },
  'hljs-template-variable': { color: '#af3a03' },
  'hljs-variable': { color: '#af3a03' },
  'hljs-title': { color: '#076678' },
  'hljs-section': { color: '#076678', fontWeight: 'bold' },
  'hljs-type': { color: '#b57614' },
  'hljs-class .hljs-title': { color: '#b57614' },
  'hljs-built_in': { color: '#427b58' },
  'hljs-name': { color: '#427b58' },
  'hljs-tag': { color: '#928374' },
  'hljs-attr': { color: '#79740e' },
  'hljs-attribute': { color: '#3c3836' },
  'hljs-meta': { color: '#665c54' },
  'hljs-meta-keyword': { color: '#665c54' },
  'hljs-meta-string': { color: '#79740e' },
  'hljs-regexp': { color: '#af3a03' },
  'hljs-link': { color: '#076678' },
  'hljs-symbol': { color: '#8f3f71' },
  'hljs-bullet': { color: '#8f3f71' },
  'hljs-subst': { color: '#3c3836' },
  'hljs-selector-id': { color: '#076678' },
  'hljs-selector-class': { color: '#076678' },
  'hljs-selector-attr': { color: '#79740e' },
  'hljs-selector-pseudo': { color: '#427b58' },
  'hljs-addition': { color: '#79740e', backgroundColor: 'rgba(121,116,14,0.1)' },
  'hljs-deletion': { color: '#9d0006', backgroundColor: 'rgba(157,0,6,0.1)' },
  'hljs-emphasis': { fontStyle: 'italic' },
  'hljs-strong': { fontWeight: 'bold' },
  'hljs-params': { color: '#3c3836' },
  'hljs-operator': { color: '#af3a03' },
  'hljs-punctuation': { color: '#3c3836' },
  'hljs-property': { color: '#427b58' },
};

export { forgeDark, forgeLight };
